### ISSUE TITLE
DOS Director fails to load large config files

### ISSUE THREAD

**Issue by FeralChild64** [MattStypa/DOS-Director#3]
When trying to load large config file, like the attached one, DOS Director fails with error:

```
Out of string space in line 0  of module DIRECTOR at address 0256:1019
```

[MENU.CFG.gz](https://github.com/user-attachments/files/17635062/MENU.CFG.gz)

I have tested on _DOSBox Staging_, current GIT main.

------

Before you ask - no, I haven't created a real file this size yet. I am currently using _Launchbox for MS-DOS Special Edition 2.0_ which - unfortunately - does not handle config files over 64 KB, forcing me to have 2 instances (for now...) installed, and I have to run the correct instance to launch the game I want (not convenient at all..).

I wanted to test this use case before the possible migration.

**Comment by MattStypa** [comment]
@FeralChild64 This will be fixed in v1.1 coming this week.

I pushed this new version very far. It should support up to 32000 items per menu AND menu depth of 32000. This means that it "COULD" support menus with more items than atoms in the universe.

BUT, I suspect that other limits will come in play before you can get there. Like DOS file size limit.

**Comment by FeralChild64** [comment]
Great! You know - 100 games, each of them with setup utility and/or alternative sound configurations (which means even more menu entries), and 64 KB quickly stops being enough.

**Comment by MattStypa** [comment]
@FeralChild64 1.1 is out
